<?xml version='1.0' encoding='UTF-8' standalone='yes'?>
<!-- Document definition -->
<!DOCTYPE MEME[
<!ELEMENT MEME (
  training_set,
  model, 
  motifs, 
  scanned_sites_summary?
)>
<!ATTLIST MEME 
  version CDATA #REQUIRED
  release CDATA #REQUIRED
>
<!-- Training-set elements -->
<!ELEMENT training_set (alphabet, ambigs, sequence*, letter_frequencies)>
<!ATTLIST training_set datafile CDATA #REQUIRED length CDATA #REQUIRED>
<!ELEMENT alphabet (letter*)>
<!ATTLIST alphabet id (amino-acid|nucleotide) #REQUIRED
                   length CDATA #REQUIRED>
<!ELEMENT ambigs (letter*)>
<!ELEMENT letter EMPTY>
<!ATTLIST letter id ID #REQUIRED>
<!ATTLIST letter symbol CDATA #REQUIRED>
<!ELEMENT sequence EMPTY>
<!ATTLIST sequence id ID #REQUIRED
                   name CDATA #REQUIRED
                   length CDATA #REQUIRED
                   weight CDATA #REQUIRED
>
<!ELEMENT letter_frequencies (alphabet_array)>

<!-- Model elements -->
<!ELEMENT model (
  command_line,
  host,
  type,
  nmotifs,
  evalue_threshold,
  object_function,
  min_width,
  max_width,
  minic,
  wg,
  ws,
  endgaps,
  minsites,
  maxsites,
  wnsites,
  prob,
  spmap,
  spfuzz,
  prior,
  beta,
  maxiter,
  distance,
  num_sequences,
  num_positions,
  seed,
  seqfrac,
  strands,
  priors_file,
  reason_for_stopping,
  background_frequencies
)>
<!ELEMENT command_line (#PCDATA)*>
<!ELEMENT host (#PCDATA)*>
<!ELEMENT type (#PCDATA)*>
<!ELEMENT nmotifs (#PCDATA)*>
<!ELEMENT evalue_threshold (#PCDATA)*>
<!ELEMENT object_function (#PCDATA)*>
<!ELEMENT min_width (#PCDATA)*>
<!ELEMENT max_width (#PCDATA)*>
<!ELEMENT minic (#PCDATA)*>
<!ELEMENT wg (#PCDATA)*>
<!ELEMENT ws (#PCDATA)*>
<!ELEMENT endgaps (#PCDATA)*>
<!ELEMENT minsites (#PCDATA)*>
<!ELEMENT maxsites (#PCDATA)*>
<!ELEMENT wnsites (#PCDATA)*>
<!ELEMENT prob (#PCDATA)*>
<!ELEMENT spmap (#PCDATA)*>
<!ELEMENT spfuzz (#PCDATA)*>
<!ELEMENT prior (#PCDATA)*>
<!ELEMENT beta (#PCDATA)*>
<!ELEMENT maxiter (#PCDATA)*>
<!ELEMENT distance (#PCDATA)*>
<!ELEMENT num_sequences (#PCDATA)*>
<!ELEMENT num_positions (#PCDATA)*>
<!ELEMENT seed (#PCDATA)*>
<!ELEMENT seqfrac (#PCDATA)*>
<!ELEMENT strands (#PCDATA)*>
<!ELEMENT priors_file (#PCDATA)*>
<!ELEMENT reason_for_stopping (#PCDATA)*>
<!ELEMENT background_frequencies (alphabet_array)>
<!ATTLIST background_frequencies source CDATA #REQUIRED>

<!-- Motif elements -->
<!ELEMENT motifs (motif*)>
<!ELEMENT motif (scores, probabilities, regular_expression?, contributing_sites)>
<!ATTLIST motif id ID #REQUIRED
                name CDATA #REQUIRED
                width CDATA #REQUIRED
                sites CDATA #REQUIRED
                llr CDATA #REQUIRED
                ic CDATA #REQUIRED
                re CDATA #REQUIRED
                bayes_threshold CDATA #REQUIRED
                e_value CDATA #REQUIRED
                elapsed_time CDATA #REQUIRED
                url CDATA ""
>
<!ELEMENT scores (alphabet_matrix)>
<!ELEMENT probabilities (alphabet_matrix)>
<!ELEMENT regular_expression (#PCDATA)*>

<!-- Contributing site elements -->
<!-- Contributing sites are motif occurences found during the motif discovery phase -->
<!ELEMENT contributing_sites (contributing_site*)>
<!ELEMENT contributing_site (left_flank, site, right_flank)>
<!ATTLIST contributing_site sequence_id IDREF #REQUIRED
                          position CDATA #REQUIRED
                          strand (plus|minus|none) 'none'
                          pvalue CDATA #REQUIRED
>
<!-- The left_flank contains the sequence for 10 bases to the left of the motif start -->
<!ELEMENT left_flank (#PCDATA)>
<!-- The site contains the sequence for the motif instance -->
<!ELEMENT site (letter_ref*)>
<!-- The right_flank contains the sequence for 10 bases to the right of the motif end -->
<!ELEMENT right_flank (#PCDATA)>

<!-- Scanned site elements -->
<!-- Scanned sites are motif occurences found during the sequence scan phase -->
<!ELEMENT scanned_sites_summary (scanned_sites*)>
<!ATTLIST scanned_sites_summary p_thresh CDATA #REQUIRED>
<!ELEMENT scanned_sites (scanned_site*)>
<!ATTLIST scanned_sites sequence_id IDREF #REQUIRED
                        pvalue CDATA #REQUIRED
                        num_sites CDATA #REQUIRED>
<!ELEMENT scanned_site EMPTY>
<!ATTLIST scanned_site  motif_id IDREF #REQUIRED
                        strand (plus|minus|none) 'none'
                        position CDATA #REQUIRED
                        pvalue CDATA #REQUIRED>

<!-- Utility elements -->
<!-- A reference to a letter in the alphabet -->
<!ELEMENT letter_ref EMPTY>
<!ATTLIST letter_ref letter_id IDREF #REQUIRED>
<!-- A alphabet-array contains one floating point value for each letter in an alphabet -->
<!ELEMENT alphabet_array (value*)>
<!ELEMENT value (#PCDATA)>
<!ATTLIST value letter_id IDREF #REQUIRED>

<!-- A alphabet_matrix contains one alphabet_array for each position in a motif -->
<!ELEMENT alphabet_matrix (alphabet_array*)>

]>
<!-- Begin document body -->
<MEME version="4.10.2" release="Thu Sep 03 15:00:54 2015 -0700">
<training_set datafile="Insensitive_up_promoters.txt" length="251">
<alphabet id="nucleotide" length="4">
<letter id="letter_A" symbol="A"/>
<letter id="letter_C" symbol="C"/>
<letter id="letter_G" symbol="G"/>
<letter id="letter_T" symbol="T"/>
</alphabet>
<ambigs>
<letter id="letter_B" symbol="B"/>
<letter id="letter_D" symbol="D"/>
<letter id="letter_H" symbol="H"/>
<letter id="letter_K" symbol="K"/>
<letter id="letter_M" symbol="M"/>
<letter id="letter_N" symbol="N"/>
<letter id="letter_R" symbol="R"/>
<letter id="letter_S" symbol="S"/>
<letter id="letter_U" symbol="U"/>
<letter id="letter_V" symbol="V"/>
<letter id="letter_W" symbol="W"/>
<letter id="letter_Y" symbol="Y"/>
<letter id="letter_star" symbol="*"/>
<letter id="letter_-" symbol="-"/>
<letter id="letter_X" symbol="X"/>
</ambigs>
<sequence id="sequence_0" name="TPS1" length="500" weight="1.000000" />
<sequence id="sequence_1" name="AGP2" length="500" weight="1.000000" />
<sequence id="sequence_2" name="ARA1" length="500" weight="1.000000" />
<sequence id="sequence_3" name="SMP1" length="500" weight="1.000000" />
<sequence id="sequence_4" name="YPC1" length="500" weight="1.000000" />
<sequence id="sequence_5" name="PCS60" length="500" weight="1.000000" />
<sequence id="sequence_6" name="TDP1" length="500" weight="1.000000" />
<sequence id="sequence_7" name="OM14" length="500" weight="1.000000" />
<sequence id="sequence_8" name="SWC5" length="500" weight="1.000000" />
<sequence id="sequence_9" name="YBR241C" length="500" weight="1.000000" />
<sequence id="sequence_10" name="ATG22" length="500" weight="1.000000" />
<sequence id="sequence_11" name="MXR2" length="500" weight="1.000000" />
<sequence id="sequence_12" name="AGP1" length="500" weight="1.000000" />
<sequence id="sequence_13" name="YCL021W-A" length="500" weight="1.000000" />
<sequence id="sequence_14" name="YCR061W" length="500" weight="1.000000" />
<sequence id="sequence_15" name="YDL218W" length="500" weight="1.000000" />
<sequence id="sequence_16" name="UGA4" length="500" weight="1.000000" />
<sequence id="sequence_17" name="YDL206W" length="500" weight="1.000000" />
<sequence id="sequence_18" name="YDL199C" length="500" weight="1.000000" />
<sequence id="sequence_19" name="STF1" length="500" weight="1.000000" />
<sequence id="sequence_20" name="MRK1" length="500" weight="1.000000" />
<sequence id="sequence_21" name="YET3" length="500" weight="1.000000" />
<sequence id="sequence_22" name="PRM7" length="500" weight="1.000000" />
<sequence id="sequence_23" name="GPD1" length="500" weight="1.000000" />
<sequence id="sequence_24" name="ERP3" length="500" weight="1.000000" />
<sequence id="sequence_25" name="GRX6" length="500" weight="1.000000" />
<sequence id="sequence_26" name="GAL3" length="500" weight="1.000000" />
<sequence id="sequence_27" name="PST2" length="500" weight="1.000000" />
<sequence id="sequence_28" name="YDR034W-B" length="500" weight="1.000000" />
<sequence id="sequence_29" name="PST1" length="500" weight="1.000000" />
<sequence id="sequence_30" name="MKC7" length="500" weight="1.000000" />
<sequence id="sequence_31" name="CPR1" length="500" weight="1.000000" />
<sequence id="sequence_32" name="AHA1" length="500" weight="1.000000" />
<sequence id="sequence_33" name="YAP6" length="500" weight="1.000000" />
<sequence id="sequence_34" name="MTH1" length="500" weight="1.000000" />
<sequence id="sequence_35" name="GIC2" length="500" weight="1.000000" />
<sequence id="sequence_36" name="TRR1" length="500" weight="1.000000" />
<sequence id="sequence_37" name="GGA1" length="500" weight="1.000000" />
<sequence id="sequence_38" name="DIT1" length="500" weight="1.000000" />
<sequence id="sequence_39" name="PDR15" length="500" weight="1.000000" />
<sequence id="sequence_40" name="TSA2" length="500" weight="1.000000" />
<sequence id="sequence_41" name="YDR476C" length="500" weight="1.000000" />
<sequence id="sequence_42" name="PAC11" length="500" weight="1.000000" />
<sequence id="sequence_43" name="LPP1" length="500" weight="1.000000" />
<sequence id="sequence_44" name="GRX2" length="500" weight="1.000000" />
<sequence id="sequence_45" name="EMI2" length="500" weight="1.000000" />
<sequence id="sequence_46" name="SNA2" length="500" weight="1.000000" />
<sequence id="sequence_47" name="PAU2" length="500" weight="1.000000" />
<sequence id="sequence_48" name="UTR4" length="500" weight="1.000000" />
<sequence id="sequence_49" name="TIR1" length="500" weight="1.000000" />
<sequence id="sequence_50" name="ZRG8" length="500" weight="1.000000" />
<sequence id="sequence_51" name="HVG1" length="500" weight="1.000000" />
<sequence id="sequence_52" name="ERG28" length="500" weight="1.000000" />
<sequence id="sequence_53" name="SPO73" length="500" weight="1.000000" />
<sequence id="sequence_54" name="RRT13" length="500" weight="1.000000" />
<sequence id="sequence_55" name="YER076C" length="500" weight="1.000000" />
<sequence id="sequence_56" name="RAD51" length="500" weight="1.000000" />
<sequence id="sequence_57" name="MAG1" length="500" weight="1.000000" />
<sequence id="sequence_58" name="PAU5" length="500" weight="1.000000" />
<sequence id="sequence_59" name="MDJ1" length="500" weight="1.000000" />
<sequence id="sequence_60" name="GSY1" length="500" weight="1.000000" />
<sequence id="sequence_61" name="YFR018C" length="500" weight="1.000000" />
<sequence id="sequence_62" name="ROG3" length="500" weight="1.000000" />
<sequence id="sequence_63" name="ULI1" length="500" weight="1.000000" />
<sequence id="sequence_64" name="TOS3" length="500" weight="1.000000" />
<sequence id="sequence_65" name="RRT6" length="500" weight="1.000000" />
<sequence id="sequence_66" name="VPS73" length="500" weight="1.000000" />
<sequence id="sequence_67" name="USE1" length="288" weight="1.000000" />
<sequence id="sequence_68" name="PRM8" length="500" weight="1.000000" />
<sequence id="sequence_69" name="ALG13" length="500" weight="1.000000" />
<sequence id="sequence_70" name="OCH1" length="500" weight="1.000000" />
<sequence id="sequence_71" name="UGA1" length="500" weight="1.000000" />
<sequence id="sequence_72" name="MTL1" length="500" weight="1.000000" />
<sequence id="sequence_73" name="SCM4" length="500" weight="1.000000" />
<sequence id="sequence_74" name="ERG25" length="500" weight="1.000000" />
<sequence id="sequence_75" name="VHT1" length="500" weight="1.000000" />
<sequence id="sequence_76" name="YGR067C" length="500" weight="1.000000" />
<sequence id="sequence_77" name="MEP1" length="500" weight="1.000000" />
<sequence id="sequence_78" name="YGR153W" length="500" weight="1.000000" />
<sequence id="sequence_79" name="ATF2" length="500" weight="1.000000" />
<sequence id="sequence_80" name="CRH1" length="500" weight="1.000000" />
<sequence id="sequence_81" name="YGR201C" length="500" weight="1.000000" />
<sequence id="sequence_82" name="RTA1" length="500" weight="1.000000" />
<sequence id="sequence_83" name="HSV2" length="500" weight="1.000000" />
<sequence id="sequence_84" name="ECM29" length="500" weight="1.000000" />
<sequence id="sequence_85" name="AIM17" length="500" weight="1.000000" />
<sequence id="sequence_86" name="QCR10" length="500" weight="1.000000" />
<sequence id="sequence_87" name="YHR054C" length="500" weight="1.000000" />
<sequence id="sequence_88" name="PPE1" length="500" weight="1.000000" />
<sequence id="sequence_89" name="HXT4" length="500" weight="1.000000" />
<sequence id="sequence_90" name="GRE3" length="500" weight="1.000000" />
<sequence id="sequence_91" name="SPO16" length="500" weight="1.000000" />
<sequence id="sequence_92" name="REC104" length="500" weight="1.000000" />
<sequence id="sequence_93" name="ERG9" length="500" weight="1.000000" />
<sequence id="sequence_94" name="FLX1" length="500" weight="1.000000" />
<sequence id="sequence_95" name="PRM5" length="500" weight="1.000000" />
<sequence id="sequence_96" name="XBP1" length="500" weight="1.000000" />
<sequence id="sequence_97" name="AIM19" length="500" weight="1.000000" />
<sequence id="sequence_98" name="RNR3" length="500" weight="1.000000" />
<sequence id="sequence_99" name="YKE4" length="500" weight="1.000000" />
<sequence id="sequence_100" name="TIR3" length="500" weight="1.000000" />
<sequence id="sequence_101" name="YIA6" length="500" weight="1.000000" />
<sequence id="sequence_102" name="CIS3" length="500" weight="1.000000" />
<sequence id="sequence_103" name="YJL118W" length="500" weight="1.000000" />
<sequence id="sequence_104" name="PRM10" length="500" weight="1.000000" />
<sequence id="sequence_105" name="YJL107C" length="500" weight="1.000000" />
<sequence id="sequence_106" name="SET4" length="500" weight="1.000000" />
<sequence id="sequence_107" name="GSM1" length="500" weight="1.000000" />
<sequence id="sequence_108" name="YJR039W" length="500" weight="1.000000" />
<sequence id="sequence_109" name="ANB1" length="500" weight="1.000000" />
<sequence id="sequence_110" name="BNA2" length="500" weight="1.000000" />
<sequence id="sequence_111" name="ECM27" length="500" weight="1.000000" />
<sequence id="sequence_112" name="STE24" length="500" weight="1.000000" />
<sequence id="sequence_113" name="STE3" length="500" weight="1.000000" />
<sequence id="sequence_114" name="RCN1" length="500" weight="1.000000" />
<sequence id="sequence_115" name="CWP1" length="500" weight="1.000000" />
<sequence id="sequence_116" name="YET1" length="500" weight="1.000000" />
<sequence id="sequence_117" name="RGT1" length="500" weight="1.000000" />
<sequence id="sequence_118" name="UGP1" length="500" weight="1.000000" />
<sequence id="sequence_119" name="YKR011C" length="500" weight="1.000000" />
<sequence id="sequence_120" name="PRY2" length="500" weight="1.000000" />
<sequence id="sequence_121" name="UTH1" length="500" weight="1.000000" />
<sequence id="sequence_122" name="TRK2" length="500" weight="1.000000" />
<sequence id="sequence_123" name="YSR3" length="500" weight="1.000000" />
<sequence id="sequence_124" name="CCP1" length="500" weight="1.000000" />
<sequence id="sequence_125" name="YKR075C" length="500" weight="1.000000" />
<sequence id="sequence_126" name="PTR2" length="500" weight="1.000000" />
<sequence id="sequence_127" name="PAU17" length="500" weight="1.000000" />
<sequence id="sequence_128" name="SSA2" length="500" weight="1.000000" />
<sequence id="sequence_129" name="YEH1" length="500" weight="1.000000" />
<sequence id="sequence_130" name="THI73" length="500" weight="1.000000" />
<sequence id="sequence_131" name="PAU23" length="500" weight="1.000000" />
<sequence id="sequence_132" name="YLR042C" length="500" weight="1.000000" />
<sequence id="sequence_133" name="YLR050C" length="500" weight="1.000000" />
<sequence id="sequence_134" name="ERG3" length="500" weight="1.000000" />
<sequence id="sequence_135" name="XYL2" length="500" weight="1.000000" />
<sequence id="sequence_136" name="YPS1" length="500" weight="1.000000" />
<sequence id="sequence_137" name="YPS3" length="500" weight="1.000000" />
<sequence id="sequence_138" name="PCD1" length="500" weight="1.000000" />
<sequence id="sequence_139" name="ACS2" length="500" weight="1.000000" />
<sequence id="sequence_140" name="YLR177W" length="500" weight="1.000000" />
<sequence id="sequence_141" name="HMX1" length="500" weight="1.000000" />
<sequence id="sequence_142" name="FRE1" length="500" weight="1.000000" />
<sequence id="sequence_143" name="CPR6" length="500" weight="1.000000" />
<sequence id="sequence_144" name="SYM1" length="500" weight="1.000000" />
<sequence id="sequence_145" name="DCS1" length="500" weight="1.000000" />
<sequence id="sequence_146" name="PIG1" length="500" weight="1.000000" />
<sequence id="sequence_147" name="YLR281C" length="500" weight="1.000000" />
<sequence id="sequence_148" name="NKP2" length="170" weight="1.000000" />
<sequence id="sequence_149" name="PEX30" length="500" weight="1.000000" />
<sequence id="sequence_150" name="MID2" length="500" weight="1.000000" />
<sequence id="sequence_151" name="CIS1" length="500" weight="1.000000" />
<sequence id="sequence_152" name="ORM2" length="500" weight="1.000000" />
<sequence id="sequence_153" name="PSY3" length="500" weight="1.000000" />
<sequence id="sequence_154" name="CTF3" length="500" weight="1.000000" />
<sequence id="sequence_155" name="YLR446W" length="500" weight="1.000000" />
<sequence id="sequence_156" name="HMG1" length="500" weight="1.000000" />
<sequence id="sequence_157" name="NTE1" length="500" weight="1.000000" />
<sequence id="sequence_158" name="CYB2" length="500" weight="1.000000" />
<sequence id="sequence_159" name="GAL80" length="500" weight="1.000000" />
<sequence id="sequence_160" name="PLB1" length="500" weight="1.000000" />
<sequence id="sequence_161" name="HXT2" length="500" weight="1.000000" />
<sequence id="sequence_162" name="ERG5" length="500" weight="1.000000" />
<sequence id="sequence_163" name="FMS1" length="500" weight="1.000000" />
<sequence id="sequence_164" name="IMP2" length="500" weight="1.000000" />
<sequence id="sequence_165" name="SNO1" length="500" weight="1.000000" />
<sequence id="sequence_166" name="YMR122W-A" length="500" weight="1.000000" />
<sequence id="sequence_167" name="OSW5" length="500" weight="1.000000" />
<sequence id="sequence_168" name="ALD2" length="500" weight="1.000000" />
<sequence id="sequence_169" name="ERG2" length="500" weight="1.000000" />
<sequence id="sequence_170" name="HOR7" length="500" weight="1.000000" />
<sequence id="sequence_171" name="SCW10" length="500" weight="1.000000" />
<sequence id="sequence_172" name="TOS6" length="500" weight="1.000000" />
<sequence id="sequence_173" name="PCL1" length="500" weight="1.000000" />
<sequence id="sequence_174" name="WSC2" length="500" weight="1.000000" />
<sequence id="sequence_175" name="HCH1" length="500" weight="1.000000" />
<sequence id="sequence_176" name="GOR1" length="500" weight="1.000000" />
<sequence id="sequence_177" name="ALP1" length="500" weight="1.000000" />
<sequence id="sequence_178" name="YNL208W" length="500" weight="1.000000" />
<sequence id="sequence_179" name="CHS1" length="500" weight="1.000000" />
<sequence id="sequence_180" name="ESBP6" length="500" weight="1.000000" />
<sequence id="sequence_181" name="CYB5" length="500" weight="1.000000" />
<sequence id="sequence_182" name="YNL092W" length="500" weight="1.000000" />
<sequence id="sequence_183" name="APJ1" length="500" weight="1.000000" />
<sequence id="sequence_184" name="MTQ1" length="500" weight="1.000000" />
<sequence id="sequence_185" name="IDH1" length="500" weight="1.000000" />
<sequence id="sequence_186" name="ATO2" length="500" weight="1.000000" />
<sequence id="sequence_187" name="YNR014W" length="500" weight="1.000000" />
<sequence id="sequence_188" name="COQ2" length="500" weight="1.000000" />
<sequence id="sequence_189" name="BIO5" length="500" weight="1.000000" />
<sequence id="sequence_190" name="BIO3" length="500" weight="1.000000" />
<sequence id="sequence_191" name="MNT4" length="500" weight="1.000000" />
<sequence id="sequence_192" name="SMF1" length="500" weight="1.000000" />
<sequence id="sequence_193" name="WSC3" length="500" weight="1.000000" />
<sequence id="sequence_194" name="MAM3" length="500" weight="1.000000" />
<sequence id="sequence_195" name="RRT8" length="500" weight="1.000000" />
<sequence id="sequence_196" name="YSP3" length="500" weight="1.000000" />
<sequence id="sequence_197" name="TIR4" length="500" weight="1.000000" />
<sequence id="sequence_198" name="TIR2" length="500" weight="1.000000" />
<sequence id="sequence_199" name="YOR019W" length="500" weight="1.000000" />
<sequence id="sequence_200" name="YOR062C" length="500" weight="1.000000" />
<sequence id="sequence_201" name="IDH2" length="500" weight="1.000000" />
<sequence id="sequence_202" name="PNS1" length="500" weight="1.000000" />
<sequence id="sequence_203" name="GSP2" length="500" weight="1.000000" />
<sequence id="sequence_204" name="YOR186W" length="500" weight="1.000000" />
<sequence id="sequence_205" name="PTP2" length="500" weight="1.000000" />
<sequence id="sequence_206" name="DGA1" length="500" weight="1.000000" />
<sequence id="sequence_207" name="YOR292C" length="500" weight="1.000000" />
<sequence id="sequence_208" name="FAA1" length="500" weight="1.000000" />
<sequence id="sequence_209" name="PDR10" length="500" weight="1.000000" />
<sequence id="sequence_210" name="PYK2" length="500" weight="1.000000" />
<sequence id="sequence_211" name="YPL247C" length="500" weight="1.000000" />
<sequence id="sequence_212" name="FLC1" length="500" weight="1.000000" />
<sequence id="sequence_213" name="GUP2" length="500" weight="1.000000" />
<sequence id="sequence_214" name="OYE3" length="500" weight="1.000000" />
<sequence id="sequence_215" name="SVS1" length="500" weight="1.000000" />
<sequence id="sequence_216" name="PEP4" length="500" weight="1.000000" />
<sequence id="sequence_217" name="ATG5" length="500" weight="1.000000" />
<sequence id="sequence_218" name="CAR1" length="500" weight="1.000000" />
<sequence id="sequence_219" name="SSE1" length="500" weight="1.000000" />
<sequence id="sequence_220" name="YPL067C" length="500" weight="1.000000" />
<sequence id="sequence_221" name="ALD6" length="500" weight="1.000000" />
<sequence id="sequence_222" name="ERG10" length="500" weight="1.000000" />
<sequence id="sequence_223" name="HST2" length="500" weight="1.000000" />
<sequence id="sequence_224" name="LSP1" length="500" weight="1.000000" />
<sequence id="sequence_225" name="YPR098C" length="500" weight="1.000000" />
<sequence id="sequence_226" name="MEP3" length="500" weight="1.000000" />
<sequence id="sequence_227" name="PIN3" length="500" weight="1.000000" />
<sequence id="sequence_228" name="KRE6" length="500" weight="1.000000" />
<sequence id="sequence_229" name="DPM1" length="500" weight="1.000000" />
<sequence id="sequence_230" name="FLC2" length="500" weight="1.000000" />
<sequence id="sequence_231" name="FRT2" length="500" weight="1.000000" />
<sequence id="sequence_232" name="FUN14" length="500" weight="1.000000" />
<sequence id="sequence_233" name="UIP3" length="500" weight="1.000000" />
<sequence id="sequence_234" name="RCR1" length="500" weight="1.000000" />
<sequence id="sequence_235" name="UGA2" length="500" weight="1.000000" />
<sequence id="sequence_236" name="GIP1" length="500" weight="1.000000" />
<sequence id="sequence_237" name="YBR053C" length="500" weight="1.000000" />
<sequence id="sequence_238" name="ALG14" length="500" weight="1.000000" />
<sequence id="sequence_239" name="YBR071W" length="500" weight="1.000000" />
<sequence id="sequence_240" name="AAC3" length="500" weight="1.000000" />
<sequence id="sequence_241" name="YBR085C-A" length="500" weight="1.000000" />
<sequence id="sequence_242" name="KHA1" length="500" weight="1.000000" />
<sequence id="sequence_243" name="YJL068C" length="500" weight="1.000000" />
<sequence id="sequence_244" name="MPM1" length="500" weight="1.000000" />
<sequence id="sequence_245" name="YHC3" length="500" weight="1.000000" />
<sequence id="sequence_246" name="TDH1" length="500" weight="1.000000" />
<sequence id="sequence_247" name="YJL045W" length="500" weight="1.000000" />
<sequence id="sequence_248" name="KAR2" length="500" weight="1.000000" />
<sequence id="sequence_249" name="YER053C-A" length="500" weight="1.000000" />
<sequence id="sequence_250" name="MIP6" length="500" weight="1.000000" />
<letter_frequencies>
<alphabet_array>
<value letter_id="letter_A">0.307</value>
<value letter_id="letter_C">0.193</value>
<value letter_id="letter_G">0.193</value>
<value letter_id="letter_T">0.307</value>
</alphabet_array>
</letter_frequencies>
</training_set>
<model>
<command_line>meme Insensitive_up_promoters.txt -dna -revcomp -nmotifs 5 -maxw 12 -oc Insensitive_up_meme -maxsize 300000 </command_line>
<host>Scotts-Mac-Pro.local</host>
<type>zoops</type>
<nmotifs>5</nmotifs>
<evalue_threshold>inf</evalue_threshold>
<object_function>E-value of product of p-values</object_function>
<min_width>8</min_width>
<max_width>12</max_width>
<minic>    0.00</minic>
<wg>11</wg>
<ws>1</ws>
<endgaps>yes</endgaps>
<minsites>2</minsites>
<maxsites>251</maxsites>
<wnsites>0.8</wnsites>
<prob>1</prob>
<spmap>uni</spmap>
<spfuzz>0.5</spfuzz>
<prior>dirichlet</prior>
<beta>0.01</beta>
<maxiter>50</maxiter>
<distance>1e-05</distance>
<num_sequences>251</num_sequences>
<num_positions>124958</num_positions>
<seed>0</seed>
<seqfrac>       1</seqfrac>
<strands>both</strands>
<priors_file></priors_file>
<reason_for_stopping>Stopped because nmotifs = 5 reached.</reason_for_stopping>
<background_frequencies source="dataset with add-one prior applied">
<alphabet_array>
<value letter_id="letter_A">0.307</value>
<value letter_id="letter_C">0.193</value>
<value letter_id="letter_G">0.193</value>
<value letter_id="letter_T">0.307</value>
</alphabet_array>
</background_frequencies>
</model>
<motifs>
<motif id="motif_1" name="1" width="12" sites="251" ic="14.0" re="12.0" llr="2088" e_value="4.4e-110" bayes_threshold="8.92434" elapsed_time="233.127497">
<scores>
<alphabet_matrix>
<alphabet_array>
<value letter_id="letter_A">116</value>
<value letter_id="letter_C">-127</value>
<value letter_id="letter_G">26</value>
<value letter_id="letter_T">-1462</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">157</value>
<value letter_id="letter_C">-1462</value>
<value letter_id="letter_G">-214</value>
<value letter_id="letter_T">-281</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">131</value>
<value letter_id="letter_C">-359</value>
<value letter_id="letter_G">21</value>
<value letter_id="letter_T">-1462</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">154</value>
<value letter_id="letter_C">-1462</value>
<value letter_id="letter_G">-84</value>
<value letter_id="letter_T">-1462</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">157</value>
<value letter_id="letter_C">-227</value>
<value letter_id="letter_G">-201</value>
<value letter_id="letter_T">-1462</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">89</value>
<value letter_id="letter_C">-279</value>
<value letter_id="letter_G">90</value>
<value letter_id="letter_T">-281</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">132</value>
<value letter_id="letter_C">-120</value>
<value letter_id="letter_G">-39</value>
<value letter_id="letter_T">-1462</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">132</value>
<value letter_id="letter_C">-189</value>
<value letter_id="letter_G">-47</value>
<value letter_id="letter_T">-295</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">117</value>
<value letter_id="letter_C">-327</value>
<value letter_id="letter_G">36</value>
<value letter_id="letter_T">-295</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">126</value>
<value letter_id="letter_C">-279</value>
<value letter_id="letter_G">29</value>
<value letter_id="letter_T">-1462</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">162</value>
<value letter_id="letter_C">-1462</value>
<value letter_id="letter_G">-179</value>
<value letter_id="letter_T">-1462</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">149</value>
<value letter_id="letter_C">-1462</value>
<value letter_id="letter_G">-51</value>
<value letter_id="letter_T">-1462</value>
</alphabet_array>
</alphabet_matrix>
</scores>
<probabilities>
<alphabet_matrix>
<alphabet_array>
<value letter_id="letter_A">0.689243</value>
<value letter_id="letter_C">0.079681</value>
<value letter_id="letter_G">0.231076</value>
<value letter_id="letter_T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">0.912351</value>
<value letter_id="letter_C">0.000000</value>
<value letter_id="letter_G">0.043825</value>
<value letter_id="letter_T">0.043825</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">0.760956</value>
<value letter_id="letter_C">0.015936</value>
<value letter_id="letter_G">0.223108</value>
<value letter_id="letter_T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">0.892430</value>
<value letter_id="letter_C">0.000000</value>
<value letter_id="letter_G">0.107570</value>
<value letter_id="letter_T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">0.912351</value>
<value letter_id="letter_C">0.039841</value>
<value letter_id="letter_G">0.047809</value>
<value letter_id="letter_T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">0.569721</value>
<value letter_id="letter_C">0.027888</value>
<value letter_id="letter_G">0.358566</value>
<value letter_id="letter_T">0.043825</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">0.768924</value>
<value letter_id="letter_C">0.083665</value>