<?xml version='1.0' encoding='UTF-8' standalone='yes'?>
<!-- Document definition -->
<!DOCTYPE MEME[
<!ELEMENT MEME (
  training_set,
  model, 
  motifs, 
  scanned_sites_summary?
)>
<!ATTLIST MEME 
  version CDATA #REQUIRED
  release CDATA #REQUIRED
>
<!-- Training-set elements -->
<!ELEMENT training_set (alphabet, ambigs, sequence*, letter_frequencies)>
<!ATTLIST training_set datafile CDATA #REQUIRED length CDATA #REQUIRED>
<!ELEMENT alphabet (letter*)>
<!ATTLIST alphabet id (amino-acid|nucleotide) #REQUIRED
                   length CDATA #REQUIRED>
<!ELEMENT ambigs (letter*)>
<!ELEMENT letter EMPTY>
<!ATTLIST letter id ID #REQUIRED>
<!ATTLIST letter symbol CDATA #REQUIRED>
<!ELEMENT sequence EMPTY>
<!ATTLIST sequence id ID #REQUIRED
                   name CDATA #REQUIRED
                   length CDATA #REQUIRED
                   weight CDATA #REQUIRED
>
<!ELEMENT letter_frequencies (alphabet_array)>

<!-- Model elements -->
<!ELEMENT model (
  command_line,
  host,
  type,
  nmotifs,
  evalue_threshold,
  object_function,
  min_width,
  max_width,
  minic,
  wg,
  ws,
  endgaps,
  minsites,
  maxsites,
  wnsites,
  prob,
  spmap,
  spfuzz,
  prior,
  beta,
  maxiter,
  distance,
  num_sequences,
  num_positions,
  seed,
  seqfrac,
  strands,
  priors_file,
  reason_for_stopping,
  background_frequencies
)>
<!ELEMENT command_line (#PCDATA)*>
<!ELEMENT host (#PCDATA)*>
<!ELEMENT type (#PCDATA)*>
<!ELEMENT nmotifs (#PCDATA)*>
<!ELEMENT evalue_threshold (#PCDATA)*>
<!ELEMENT object_function (#PCDATA)*>
<!ELEMENT min_width (#PCDATA)*>
<!ELEMENT max_width (#PCDATA)*>
<!ELEMENT minic (#PCDATA)*>
<!ELEMENT wg (#PCDATA)*>
<!ELEMENT ws (#PCDATA)*>
<!ELEMENT endgaps (#PCDATA)*>
<!ELEMENT minsites (#PCDATA)*>
<!ELEMENT maxsites (#PCDATA)*>
<!ELEMENT wnsites (#PCDATA)*>
<!ELEMENT prob (#PCDATA)*>
<!ELEMENT spmap (#PCDATA)*>
<!ELEMENT spfuzz (#PCDATA)*>
<!ELEMENT prior (#PCDATA)*>
<!ELEMENT beta (#PCDATA)*>
<!ELEMENT maxiter (#PCDATA)*>
<!ELEMENT distance (#PCDATA)*>
<!ELEMENT num_sequences (#PCDATA)*>
<!ELEMENT num_positions (#PCDATA)*>
<!ELEMENT seed (#PCDATA)*>
<!ELEMENT seqfrac (#PCDATA)*>
<!ELEMENT strands (#PCDATA)*>
<!ELEMENT priors_file (#PCDATA)*>
<!ELEMENT reason_for_stopping (#PCDATA)*>
<!ELEMENT background_frequencies (alphabet_array)>
<!ATTLIST background_frequencies source CDATA #REQUIRED>

<!-- Motif elements -->
<!ELEMENT motifs (motif*)>
<!ELEMENT motif (scores, probabilities, regular_expression?, contributing_sites)>
<!ATTLIST motif id ID #REQUIRED
                name CDATA #REQUIRED
                width CDATA #REQUIRED
                sites CDATA #REQUIRED
                llr CDATA #REQUIRED
                ic CDATA #REQUIRED
                re CDATA #REQUIRED
                bayes_threshold CDATA #REQUIRED
                e_value CDATA #REQUIRED
                elapsed_time CDATA #REQUIRED
                url CDATA ""
>
<!ELEMENT scores (alphabet_matrix)>
<!ELEMENT probabilities (alphabet_matrix)>
<!ELEMENT regular_expression (#PCDATA)*>

<!-- Contributing site elements -->
<!-- Contributing sites are motif occurences found during the motif discovery phase -->
<!ELEMENT contributing_sites (contributing_site*)>
<!ELEMENT contributing_site (left_flank, site, right_flank)>
<!ATTLIST contributing_site sequence_id IDREF #REQUIRED
                          position CDATA #REQUIRED
                          strand (plus|minus|none) 'none'
                          pvalue CDATA #REQUIRED
>
<!-- The left_flank contains the sequence for 10 bases to the left of the motif start -->
<!ELEMENT left_flank (#PCDATA)>
<!-- The site contains the sequence for the motif instance -->
<!ELEMENT site (letter_ref*)>
<!-- The right_flank contains the sequence for 10 bases to the right of the motif end -->
<!ELEMENT right_flank (#PCDATA)>

<!-- Scanned site elements -->
<!-- Scanned sites are motif occurences found during the sequence scan phase -->
<!ELEMENT scanned_sites_summary (scanned_sites*)>
<!ATTLIST scanned_sites_summary p_thresh CDATA #REQUIRED>
<!ELEMENT scanned_sites (scanned_site*)>
<!ATTLIST scanned_sites sequence_id IDREF #REQUIRED
                        pvalue CDATA #REQUIRED
                        num_sites CDATA #REQUIRED>
<!ELEMENT scanned_site EMPTY>
<!ATTLIST scanned_site  motif_id IDREF #REQUIRED
                        strand (plus|minus|none) 'none'
                        position CDATA #REQUIRED
                        pvalue CDATA #REQUIRED>

<!-- Utility elements -->
<!-- A reference to a letter in the alphabet -->
<!ELEMENT letter_ref EMPTY>
<!ATTLIST letter_ref letter_id IDREF #REQUIRED>
<!-- A alphabet-array contains one floating point value for each letter in an alphabet -->
<!ELEMENT alphabet_array (value*)>
<!ELEMENT value (#PCDATA)>
<!ATTLIST value letter_id IDREF #REQUIRED>

<!-- A alphabet_matrix contains one alphabet_array for each position in a motif -->
<!ELEMENT alphabet_matrix (alphabet_array*)>

]>
<!-- Begin document body -->
<MEME version="4.10.2" release="Thu Sep 03 15:00:54 2015 -0700">
<training_set datafile="Insensitive_down_promoters.txt" length="85">
<alphabet id="nucleotide" length="4">
<letter id="letter_A" symbol="A"/>
<letter id="letter_C" symbol="C"/>
<letter id="letter_G" symbol="G"/>
<letter id="letter_T" symbol="T"/>
</alphabet>
<ambigs>
<letter id="letter_B" symbol="B"/>
<letter id="letter_D" symbol="D"/>
<letter id="letter_H" symbol="H"/>
<letter id="letter_K" symbol="K"/>
<letter id="letter_M" symbol="M"/>
<letter id="letter_N" symbol="N"/>
<letter id="letter_R" symbol="R"/>
<letter id="letter_S" symbol="S"/>
<letter id="letter_U" symbol="U"/>
<letter id="letter_V" symbol="V"/>
<letter id="letter_W" symbol="W"/>
<letter id="letter_Y" symbol="Y"/>
<letter id="letter_star" symbol="*"/>
<letter id="letter_-" symbol="-"/>
<letter id="letter_X" symbol="X"/>
</ambigs>
<sequence id="sequence_0" name="RIB7" length="500" weight="1.000000" />
<sequence id="sequence_1" name="KNH1" length="500" weight="1.000000" />
<sequence id="sequence_2" name="GCV1" length="500" weight="1.000000" />
<sequence id="sequence_3" name="DAS2" length="500" weight="1.000000" />
<sequence id="sequence_4" name="TPI1" length="500" weight="1.000000" />
<sequence id="sequence_5" name="MAK21" length="500" weight="1.000000" />
<sequence id="sequence_6" name="PPH3" length="500" weight="1.000000" />
<sequence id="sequence_7" name="TFB5" length="500" weight="1.000000" />
<sequence id="sequence_8" name="PHM6" length="500" weight="1.000000" />
<sequence id="sequence_9" name="BFR2" length="500" weight="1.000000" />
<sequence id="sequence_10" name="SRB7" length="500" weight="1.000000" />
<sequence id="sequence_11" name="YHP1" length="500" weight="1.000000" />
<sequence id="sequence_12" name="MFA1" length="500" weight="1.000000" />
<sequence id="sequence_13" name="ITR1" length="500" weight="1.000000" />
<sequence id="sequence_14" name="YDR514C" length="500" weight="1.000000" />
<sequence id="sequence_15" name="HIS1" length="500" weight="1.000000" />
<sequence id="sequence_16" name="DSE1" length="500" weight="1.000000" />
<sequence id="sequence_17" name="VTC2" length="500" weight="1.000000" />
<sequence id="sequence_18" name="MIG2" length="500" weight="1.000000" />
<sequence id="sequence_19" name="OLE1" length="500" weight="1.000000" />
<sequence id="sequence_20" name="YGR017W" length="500" weight="1.000000" />
<sequence id="sequence_21" name="MUP1" length="500" weight="1.000000" />
<sequence id="sequence_22" name="UPF3" length="500" weight="1.000000" />
<sequence id="sequence_23" name="CLB1" length="500" weight="1.000000" />
<sequence id="sequence_24" name="NSR1" length="500" weight="1.000000" />
<sequence id="sequence_25" name="YHB1" length="500" weight="1.000000" />
<sequence id="sequence_26" name="PEX21" length="500" weight="1.000000" />
<sequence id="sequence_27" name="EFG1" length="500" weight="1.000000" />
<sequence id="sequence_28" name="YHI9" length="500" weight="1.000000" />
<sequence id="sequence_29" name="IPI1" length="500" weight="1.000000" />
<sequence id="sequence_30" name="DSE2" length="500" weight="1.000000" />
<sequence id="sequence_31" name="QDR2" length="500" weight="1.000000" />
<sequence id="sequence_32" name="RPI1" length="500" weight="1.000000" />
<sequence id="sequence_33" name="ACO2" length="500" weight="1.000000" />
<sequence id="sequence_34" name="SAP185" length="500" weight="1.000000" />
<sequence id="sequence_35" name="LSM8" length="500" weight="1.000000" />
<sequence id="sequence_36" name="JJJ3" length="500" weight="1.000000" />
<sequence id="sequence_37" name="MNN4" length="500" weight="1.000000" />
<sequence id="sequence_38" name="GPM1" length="500" weight="1.000000" />
<sequence id="sequence_39" name="AAT1" length="500" weight="1.000000" />
<sequence id="sequence_40" name="VPS24" length="500" weight="1.000000" />
<sequence id="sequence_41" name="URB1" length="500" weight="1.000000" />
<sequence id="sequence_42" name="MET14" length="500" weight="1.000000" />
<sequence id="sequence_43" name="MEH1" length="500" weight="1.000000" />
<sequence id="sequence_44" name="GAP1" length="500" weight="1.000000" />
<sequence id="sequence_45" name="DAD2" length="500" weight="1.000000" />
<sequence id="sequence_46" name="FYV7" length="500" weight="1.000000" />
<sequence id="sequence_47" name="SRN2" length="500" weight="1.000000" />
<sequence id="sequence_48" name="ASP3-1" length="500" weight="1.000000" />
<sequence id="sequence_49" name="ASP3-2" length="500" weight="1.000000" />
<sequence id="sequence_50" name="ASP3-3" length="500" weight="1.000000" />
<sequence id="sequence_51" name="ASP3-4" length="500" weight="1.000000" />
<sequence id="sequence_52" name="YML108W" length="500" weight="1.000000" />
<sequence id="sequence_53" name="IOC4" length="500" weight="1.000000" />
<sequence id="sequence_54" name="FAA4" length="500" weight="1.000000" />
<sequence id="sequence_55" name="MFA2" length="500" weight="1.000000" />
<sequence id="sequence_56" name="EAF7" length="500" weight="1.000000" />
<sequence id="sequence_57" name="NRK1" length="500" weight="1.000000" />
<sequence id="sequence_58" name="SWS2" length="500" weight="1.000000" />
<sequence id="sequence_59" name="AQR1" length="500" weight="1.000000" />
<sequence id="sequence_60" name="DCP1" length="500" weight="1.000000" />
<sequence id="sequence_61" name="NOP8" length="500" weight="1.000000" />
<sequence id="sequence_62" name="ZEO1" length="500" weight="1.000000" />
<sequence id="sequence_63" name="IZH2" length="500" weight="1.000000" />
<sequence id="sequence_64" name="STD1" length="500" weight="1.000000" />
<sequence id="sequence_65" name="RAS1" length="500" weight="1.000000" />
<sequence id="sequence_66" name="RGS2" length="500" weight="1.000000" />
<sequence id="sequence_67" name="YOR111W" length="500" weight="1.000000" />
<sequence id="sequence_68" name="LEO1" length="500" weight="1.000000" />
<sequence id="sequence_69" name="ODC2" length="500" weight="1.000000" />
<sequence id="sequence_70" name="DFR1" length="500" weight="1.000000" />
<sequence id="sequence_71" name="SPS4" length="500" weight="1.000000" />
<sequence id="sequence_72" name="TYE7" length="500" weight="1.000000" />
<sequence id="sequence_73" name="YIG1" length="500" weight="1.000000" />
<sequence id="sequence_74" name="NAN1" length="500" weight="1.000000" />
<sequence id="sequence_75" name="PDR12" length="500" weight="1.000000" />
<sequence id="sequence_76" name="TRM44" length="500" weight="1.000000" />
<sequence id="sequence_77" name="MAK3" length="500" weight="1.000000" />
<sequence id="sequence_78" name="SRP54" length="500" weight="1.000000" />
<sequence id="sequence_79" name="CTR1" length="500" weight="1.000000" />
<sequence id="sequence_80" name="MET16" length="500" weight="1.000000" />
<sequence id="sequence_81" name="ECM13" length="500" weight="1.000000" />
<sequence id="sequence_82" name="FUI1" length="500" weight="1.000000" />
<sequence id="sequence_83" name="RER2" length="500" weight="1.000000" />
<sequence id="sequence_84" name="TIP1" length="500" weight="1.000000" />
<letter_frequencies>
<alphabet_array>
<value letter_id="letter_A">0.317</value>
<value letter_id="letter_C">0.183</value>
<value letter_id="letter_G">0.183</value>
<value letter_id="letter_T">0.317</value>
</alphabet_array>
</letter_frequencies>
</training_set>
<model>
<command_line>meme Insensitive_down_promoters.txt -dna -revcomp -nmotifs 5 -maxw 12 -oc Insensitive_down_meme -maxsize 300000 </command_line>
<host>Scotts-Mac-Pro.local</host>
<type>zoops</type>
<nmotifs>5</nmotifs>
<evalue_threshold>inf</evalue_threshold>
<object_function>E-value of product of p-values</object_function>
<min_width>8</min_width>
<max_width>12</max_width>
<minic>    0.00</minic>
<wg>11</wg>
<ws>1</ws>
<endgaps>yes</endgaps>
<minsites>2</minsites>
<maxsites>85</maxsites>
<wnsites>0.8</wnsites>
<prob>1</prob>
<spmap>uni</spmap>
<spfuzz>0.5</spfuzz>
<prior>dirichlet</prior>
<beta>0.01</beta>
<maxiter>50</maxiter>
<distance>1e-05</distance>
<num_sequences>85</num_sequences>
<num_positions>42500</num_positions>
<seed>0</seed>
<seqfrac>       1</seqfrac>
<strands>both</strands>
<priors_file></priors_file>
<reason_for_stopping>Stopped because nmotifs = 5 reached.</reason_for_stopping>
<background_frequencies source="dataset with add-one prior applied">
<alphabet_array>
<value letter_id="letter_A">0.317</value>
<value letter_id="letter_C">0.183</value>
<value letter_id="letter_G">0.183</value>
<value letter_id="letter_T">0.317</value>
</alphabet_array>
</background_frequencies>
</model>
<motifs>
<motif id="motif_1" name="1" width="12" sites="85" ic="15.8" re="13.4" llr="792" e_value="1.8e-055" bayes_threshold="9.24901" elapsed_time="30.059382">
<scores>
<alphabet_matrix>
<alphabet_array>
<value letter_id="letter_A">-43</value>
<value letter_id="letter_C">-5</value>
<value letter_id="letter_G">169</value>
<value letter_id="letter_T">-1305</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">125</value>
<value letter_id="letter_C">13</value>
<value letter_id="letter_G">-196</value>
<value letter_id="letter_T">-1305</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">166</value>
<value letter_id="letter_C">-1305</value>
<value letter_id="letter_G">-1305</value>
<value letter_id="letter_T">-1305</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">127</value>
<value letter_id="letter_C">-1305</value>
<value letter_id="letter_G">13</value>
<value letter_id="letter_T">-317</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">140</value>
<value letter_id="letter_C">-96</value>
<value letter_id="letter_G">-137</value>
<value letter_id="letter_T">-1305</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">97</value>
<value letter_id="letter_C">-1305</value>
<value letter_id="letter_G">85</value>
<value letter_id="letter_T">-275</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">144</value>
<value letter_id="letter_C">-1305</value>
<value letter_id="letter_G">-37</value>
<value letter_id="letter_T">-1305</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">166</value>
<value letter_id="letter_C">-1305</value>
<value letter_id="letter_G">-1305</value>
<value letter_id="letter_T">-1305</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">140</value>
<value letter_id="letter_C">-1305</value>
<value letter_id="letter_G">-237</value>
<value letter_id="letter_T">-129</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">113</value>
<value letter_id="letter_C">-295</value>
<value letter_id="letter_G">63</value>
<value letter_id="letter_T">-1305</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">149</value>
<value letter_id="letter_C">-1305</value>
<value letter_id="letter_G">-163</value>
<value letter_id="letter_T">-275</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">166</value>
<value letter_id="letter_C">-1305</value>
<value letter_id="letter_G">-1305</value>
<value letter_id="letter_T">-1305</value>
</alphabet_array>
</alphabet_matrix>
</scores>
<probabilities>
<alphabet_matrix>
<alphabet_array>
<value letter_id="letter_A">0.235294</value>
<value letter_id="letter_C">0.176471</value>
<value letter_id="letter_G">0.588235</value>
<value letter_id="letter_T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">0.752941</value>
<value letter_id="letter_C">0.200000</value>
<value letter_id="letter_G">0.047059</value>
<value letter_id="letter_T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">1.000000</value>
<value letter_id="letter_C">0.000000</value>
<value letter_id="letter_G">0.000000</value>
<value letter_id="letter_T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">0.764706</value>
<value letter_id="letter_C">0.000000</value>
<value letter_id="letter_G">0.200000</value>
<value letter_id="letter_T">0.035294</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">0.835294</value>
<value letter_id="letter_C">0.094118</value>
<value letter_id="letter_G">0.070588</value>
<value letter_id="letter_T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">0.623529</value>
<value letter_id="letter_C">0.000000</value>
<value letter_id="letter_G">0.329412</value>
<value letter_id="letter_T">0.047059</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">0.858824</value>
<value letter_id="letter_C">0.000000</value>
<value letter_id="letter_G">0.141176</value>
<value letter_id="letter_T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">1.000000</value>
<value letter_id="letter_C">0.000000</value>
<value letter_id="letter_G">0.000000</value>
<value letter_id="letter_T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">0.835294</value>
<value letter_id="letter_C">0.000000</value>
<value letter_id="letter_G">0.035294</value>
<value letter_id="letter_T">0.129412</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">0.694118</value>
<value letter_id="letter_C">0.023529</value>
<value letter_id="letter_G">0.282353</value>
<value letter_id="letter_T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">0.894118</value>
<value letter_id="letter_C">0.000000</value>
<value letter_id="letter_G">0.058824</value>
<value letter_id="letter_T">0.047059</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">1.000000</value>
<value letter_id="letter_C">0.000000</value>
<value letter_id="letter_G">0.000000</value>
<value letter_id="letter_T">0.000000</value>
</alphabet_array>
</alphabet_matrix>
</probabilities>
<regular_expression>
[GA][AC]A[AG]A[AG]AAA[AG]AA
</regular_expression>
<contributing_sites>
<contributing_site sequence_id="sequence_83" position="415" strand="plus" pvalue="5.94e-07" >
<left_flank>TGCTTAGAAT</left_flank>
<site>
<letter_ref letter_id="letter_G"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
</site>
<right_flank>AATTTTCGTA</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_69" position="273" strand="minus" pvalue="5.94e-07" >
<left_flank>CGAAAAAACT</left_flank>
<site>
<letter_ref letter_id="letter_G"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
</site>
<right_flank>GTTCCAGAGG</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_65" position="166" strand="plus" pvalue="5.94e-07" >
<left_flank>AAACCCGTAG</left_flank>
<site>
<letter_ref letter_id="letter_G"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
</site>
<right_flank>GCACGAAGAA</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_35" position="464" strand="plus" pvalue="5.94e-07" >
<left_flank>GGCGTAAAGG</left_flank>
<site>
<letter_ref letter_id="letter_G"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
</site>
<right_flank>CTAATCTTAC</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_33" position="248" strand="minus" pvalue="5.94e-07" >
<left_flank>TCAAGAGCGT</left_flank>
<site>
<letter_ref letter_id="letter_G"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
</site>
<right_flank>AAAAAAAAAA</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_32" position="460" strand="minus" pvalue="5.94e-07" >
<left_flank>AAAATGATGA</left_flank>
<site>
<letter_ref letter_id="letter_G"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
</site>
<right_flank>AAGACTTAAA</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_27" position="255" strand="plus" pvalue="5.94e-07" >
<left_flank>GAGATTCTTT</left_flank>
<site>
<letter_ref letter_id="letter_G"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
</site>
<right_flank>GCATTGAGAA</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_21" position="82" strand="plus" pvalue="5.94e-07" >
<left_flank>CACAGAAAAA</left_flank>
<site>
<letter_ref letter_id="letter_G"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
</site>
<right_flank>AGAAACGGCG</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_20" position="234" strand="minus" pvalue="5.94e-07" >
<left_flank>AAATGCTGCG</left_flank>
<site>
<letter_ref letter_id="letter_G"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
</site>
<right_flank>ACCTTTCGAC</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_15" position="27" strand="plus" pvalue="5.94e-07" >
<left_flank>AAGCCAAAAA</left_flank>
<site>
<letter_ref letter_id="letter_G"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
</site>
<right_flank>GTAAGAATGC</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_71" position="97" strand="plus" pvalue="9.38e-07" >
<left_flank>GAAAAGAGCA</left_flank>
<site>
<letter_ref letter_id="letter_G"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_G"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
</site>
<right_flank>CGCCGGTCTC</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_39" position="383" strand="plus" pvalue="9.38e-07" >
<left_flank>CGTCGCAATT</left_flank>
<site>
<letter_ref letter_id="letter_G"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_G"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
</site>
<right_flank>AAAATACAGA</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_28" position="369" strand="minus" pvalue="1.48e-06" >
<left_flank>ATAAATGAAC</left_flank>
<site>
<letter_ref letter_id="letter_G"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_G"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_G"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
</site>
<right_flank>TTCAAGAGGC</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_66" position="94" strand="plus" pvalue="2.17e-06" >
<left_flank>GAAATTGAAA</left_flank>
<site>
<letter_ref letter_id="letter_G"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_G"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
</site>
<right_flank>AACATAATCA</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_51" position="326" strand="plus" pvalue="2.17e-06" >
<left_flank>GCTTGCTATC</left_flank>
<site>
<letter_ref letter_id="letter_G"/>
<letter_ref letter_id="letter_C"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
</site>
<right_flank>AAATCAATTT</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_50" position="326" strand="plus" pvalue="2.17e-06" >
<left_flank>GCTTGCTATC</left_flank>
<site>
<letter_ref letter_id="letter_G"/>
<letter_ref letter_id="letter_C"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
</site>
<right_flank>AAATCAATTT</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_49" position="326" strand="plus" pvalue="2.17e-06" >
<left_flank>GCTTGCTATC</left_flank>
<site>
<letter_ref letter_id="letter_G"/>
<letter_ref letter_id="letter_C"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
</site>
<right_flank>AAATCAATTT</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_48" position="326" strand="plus" pvalue="2.17e-06" >
<left_flank>GCTTGCTATC</left_flank>
<site>
<letter_ref letter_id="letter_G"/>
<letter_ref letter_id="letter_C"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>
<letter_ref letter_id="letter_A"/>